spring:
  application:
    name: firstSpringApp
  data:
    mongodb:
      uri: mongodb+srv://harshal:992345@cluster0.mziiy.mongodb.net/?appName=Cluster0
      database: journaldb
      auto-index-creation: true

server:
  port: 8080
