spring:
#  redis:
#    host: localhost
#    port: 6379
  data:
    redis:
      url: redis://default:g2AXxCTxIw00zHm9UeGyjTlPGSrSukkj@redis-15187.crce182.ap-south-1-1.ec2.cloud.redislabs.com:15187
#      host: redis-15187.crce182.ap-south-1-1.ec2.cloud.redislabs.com
#      port: 15187
#      username: default
#      password: g2AXxCTxIw00zHm9UeGyjTlPGSrSukkj
#      ssl:
#        enabled: true
#      timeout: 2000

  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: harshalshelke94@gmail.com
    password: cakk zonk lior agtl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

weather:
  api:
    key: "rbmvcWfFV9y73zrNFAnzaA==LE64pMS1LBIDsdsm"